name: Ansible CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
# hi
#hllo

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Hello Ansible!
        run: echo "Hello from Ansible!"